app/web/challenges/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, IntegerField, SelectField, StringField
from wtforms.validators import DataRequired, InputRequired, NumberRange, Optional, ValidationError

import os

class LocalDirRequired:
    def __init__(self, message='Directory does not exist.'):
        self.message = message

    def __call__(self, form, field):
        if not os.path.isdir(field.data):
            raise ValidationError(self.message)

class LocalFileRequired:
    def __init__(self, message='File does not exist.'):
        self.message = message

    def __call__(self, form, field):
        if not os.path.isfile(field.data):
            raise ValidationError(self.message)

LANGUAGES = [
    ('c',     'C'),
    ('cpp',   'C++'),
    ('go',    'Go'),
    ('nim',   'Nim'),
    ('rust',  'Rust'),
    ('swift', 'Swift')
]

class ChallengeForm(FlaskForm):
    name = StringField('Name',  validators = [
        DataRequired()
    ])

    value = IntegerField('Value', validators = [
        DataRequired(),
        NumberRange(min=0)
    ])

    language = SelectField('Language', choices=LANGUAGES, validators = [
        DataRequired()
    ])

    functions = StringField('Functions', validators = [
        DataRequired()
    ])

    hidden = BooleanField('Hidden', default=False)

    container = StringField('Container', validators = [
        DataRequired()
    ])

    builder = StringField('Path to Build Script', validators = [
        DataRequired(),
        LocalFileRequired()
    ])

    tester = StringField('Path to Test Script', validators = [
        DataRequired(),
        LocalFileRequired()
    ])

    folder = StringField('Path to Challenge Folder', validators = [
        DataRequired(),
        LocalDirRequired()
    ])

    binary = StringField('Path to Binary', validators = [
        DataRequired(),
        LocalFileRequired()
    ])

    disasm = StringField('Path to Disassembly', validators = [
        Optional(),
        LocalFileRequired()
    ])

    deccode = StringField('Path to Decompiler results', validators = [
        Optional(),
        LocalFileRequired()
    ])

    decomp = StringField('Path to Starter Code', validators = [
        DataRequired(),
        LocalFileRequired()
    ])

    binja_url = StringField('Binary Ninja Cloud URL', validators = [
        Optional()
    ])

    @staticmethod
    def from_challenge_info(info):
        return ChallengeForm(
            name      = info.name,
            value     = info.value,
            language  = info.language,

            functions = ' '.join(info.functions),
            container = info.container,
            builder   = info.builder,
            tester    = info.tester,

            folder    = info.folder,
            # source    = info.source,
            decomp    = info.starter,
            binary    = info.binary,
            disasm    = info.disasm,
            deccode   = info.deccode
        )


class ChallengeUploadForm(FlaskForm):
    config_path = StringField('Config File',
        description = 'Path to a config file on the app server.',
        validators  = [
            InputRequired(),
            LocalFileRequired()
        ]
    )

app/web/challenges/routes.py
from flask import Blueprint, current_app, flash, redirect, render_template, request, send_file, url_for
from flask_login import current_user
from .forms import ChallengeForm, ChallengeUploadForm

from ...lib.challs  import ChallengeImpl
from ...lib.differ  import diff_all
from ...lib.models  import db, Account, Challenge, Submission
from ...lib.require import require
from ...lib.scoring import solves
from ...lib.timing  import now

import datetime
import json
import os
import yaml

def readfile(path):
    with open(path) as file:
        return file.read()

blueprint = Blueprint('challenges', __name__)

@blueprint.route('/challenges', methods=['GET'])
def index():
    begtime = current_app.config.get('START_TIME')
    if not current_user.is_admin() and begtime and begtime > now():
        challenges = []
        scoremap   = {}
    else:
        challenges = Challenge.query.order_by('name')
        if not current_user.is_admin():
            challenges = challenges.filter_by(hidden=False)
        challenges = challenges.all()
        scoremap   = {s.id:s.score for s in solves(current_user.get_owner_id())}
    return render_template('challenges/index.html', challenges=challenges, solves=scoremap)


@blueprint.route('/challenges/new', methods=['GET', 'POST'])
@require(admin=True)
def new():
    form = ChallengeForm()
    if form.validate_on_submit():
        challenge = Challenge.from_form(form)
        db.session.add(challenge)
        db.session.commit()
        flash('Challenge created.')
        return redirect(url_for('challenges.index'))
    return render_template('challenges/new.html', form=form)


@blueprint.route('/challenges/upload', methods=['GET', 'POST'])
@require(admin=True)
def upload():
    upload_form = ChallengeUploadForm()
    if upload_form.validate_on_submit():
        from ...lib.challs import load
        infos = load(upload_form.config_path.data)

        for info in infos:
            form = ChallengeForm.from_challenge_info(info)
            if not form.validate():
                db.session.rollback()
                return render_template('challenges/new.html', form=form)
            challenge = Challenge.from_form(form)
            db.session.add(challenge)
        db.session.commit()
        flash('Upload successful.')
        return redirect(url_for('challenges.index'))
    return render_template('challenges/upload.html', form=upload_form)


@blueprint.route('/challenges/<id>', methods=['GET'])
@require(user=True, running=True)
def show(id):
    challenge  = Challenge.query.get_or_404(id)
    submission = Submission.query.filter_by(
        user_id      = current_user.get_id(),
        challenge_id = challenge.id
    ).order_by(
        Submission.id.desc()
    ).first()

    if submission:
        decomp = submission.submission
        parent = submission.id
    else:
        decomp = readfile(challenge.decomp)
        parent = 0

    with open(challenge.disasm) as file:
        target = yaml.safe_load(file)

    with open(challenge.deccode) as file:
        decompile = yaml.safe_load(file)

    return render_template('challenges/editor.html',
        challenge = challenge,
        target    = target,
        decompile = decompile,
        decomp    = decomp,
        parent    = parent
    )


@blueprint.route('/challenges/<id>', methods=['POST'])
@require(user=True, running=True)
def compile(id):
    # endtime = current_app.config.get('END_TIME')
    # if endtime and endtime <= now():
    #     return 'The competition has ended.', 403

    challenge  = Challenge.query.get_or_404(id)
    submission = Submission(
        challenge  = challenge,
        user_id    = current_user.get_id(),
        owner_id   = current_user.get_owner_id(),
        ip_address = request.remote_addr,
        submission = request.form['source'],
        parent_id  = request.form.get('parent'),
        created_at = now()
    )

    os.makedirs(submission.folder, exist_ok=True)
    with open(submission.source, 'w') as file:
        file.write(submission.submission)

    build = submission.compile()
    if build.returncode != 0:
        submission.test_score = 0.0
        submission.diff_score = 0.0
        submission.diff_bonus = 0.0
        submission.score      = 0.0
        if not current_user.is_admin():
            db.session.add(submission)
            db.session.commit()

        return json.dumps({
            'id':     submission.id,
            'stdout': build.stdout
        })

    disasm = submission.disassemble()
    with open(challenge.disasm) as file:
        target = yaml.safe_load(file)
    hunks, delta = diff_all(disasm, target)
    tests = submission.test()

    submission.test_score = tests['pass'] / tests['total']
    submission.diff_score = delta[1]      / delta[3]
    submission.diff_bonus = 1.0 if submission.diff_score == 1.0 else 0.0
    submission.score      = sum([
        0.2 * submission.test_score,
        0.6 * submission.diff_score,
        0.2 * submission.diff_bonus
    ])

    if not current_user.is_admin():
        db.session.add(submission)
        db.session.commit()

    return json.dumps({
        'id':        submission.id,
        'stdout':    build.stdout,
        'functions': hunks,
        'scores':    {
            'ins':   delta[0],
            'del':   delta[2],
            'tests': submission.test_score,
            'diffs': submission.diff_score,
            'bonus': submission.diff_bonus,
            'total': submission.score
        }
    })


@blueprint.route('/challenges/<id>/download', methods=['GET'])
@require(user=True)
def download(id):
    begtime = current_app.config.get('START_TIME')
    if begtime and begtime > now():
        flash('The competition hasn\'t started yet.', 'warning')
        return redirect(url_for('challenges.index'))

    challenge = Challenge.query.get_or_404(id)
    return send_file(challenge.binary,
        mimetype      = 'application/octet-stream',
        download_name = challenge.name,
        as_attachment = True
    )


@blueprint.route('/challenges/<id>/edit', methods=['GET', 'POST'])
@require(admin=True)
def edit(id):
    challenge = Challenge.query.get_or_404(id)
    form = ChallengeForm(obj=challenge)
    if form.validate_on_submit():
        challenge.set_attributes(form)
        db.session.add(challenge)
        db.session.commit()

        flash('Challenge updated.')
        return redirect(url_for('challenges.index'))
    return render_template('challenges/edit.html', challenge=challenge, form=form)


@blueprint.route('/challenges/<id>', methods=['DELETE'])
@require(admin=True)
def delete(id):
    challenge = Challenge.filter_by(id=id).delete()
    flash('Challenge deleted.')
    return redirect(url_for('challenges.index'))

@blueprint.route('/challenges/<id>/submissions.json', methods=['GET'])
@require(user=True, running=True)
def submissions(id):
    subquery = db.session.query(
        db.func.max(Submission.id).label('submission_id'),
        Submission.user_id.label('user_id')
    ).select_from(
        Submission
    ).filter(
        Submission.challenge_id == id,
        Submission.owner_id     == current_user.get_owner_id()
    ).group_by(
        Submission.user_id
    ).subquery()

    query = db.session.query(
        Submission.id.label('id'),
        Account.name.label('author'),
        Submission.score.label('score')
    ).select_from(
        subquery
    ).join(
        Account, Account.id == subquery.c.user_id
    ).join(
        Submission, Submission.id == subquery.c.submission_id
    )

    result = [{'id': 0, 'author': 'Starter Code', 'score': 0}]
    for row in query.all():
        result.append({
            'id':     row.id,
            'author': row.author,
            'score':  row.score
        })

    return json.dumps(result)

@blueprint.route('/challenges/<cid>/submissions/<sid>.json', methods=['GET'])
@require(user=True, running=True)
def submission(cid, sid):
    if str(sid) == '0':
        challenge = Challenge.query.get_or_404(cid)
        return json.dumps({
            'id':     0,
            'source': readfile(challenge.decomp)
        })

    submission = Submission.query.filter_by(
        owner_id     = current_user.get_owner_id(),
        challenge_id = cid,
        id           = sid
    ).first_or_404()

    return json.dumps({
        'id':     sid,
        'source': submission.submission
    })

app/web/scores/routes.py
from flask import Blueprint, current_app, jsonify, render_template, request
import datetime

from ...lib.models  import Challenge
from ...lib.scoring import firsts, scores
from ...lib.timing  import now

blueprint = Blueprint('scores', __name__)


@blueprint.route('/scoreboard', methods=['GET'])
def html():
    endtime = current_app.config.get('END_TIME')
    if endtime and endtime <= now():
        official = (request.args.get('scores') == 'official')
        if not official: endtime = None
    else:
        official = None

    teams = scores(end=endtime)
    return render_template('scores/scoreboard.html', teams=teams, official=official)


@blueprint.route('/firstblood', methods=['GET'])
def firstblood():
    return render_template('scores/firstblood.html', submissions=firsts())


@blueprint.route('/scoreboard.json', methods=['GET'])
def json():
    endtime   = current_app.config.get('END_TIME')
    standings = []

    for team in scores(end=endtime):
        standings.append({
            'team':  team.name,
            'score': round(team.score, 2),
            'pos':   team.rank
        })

    return jsonify({'standings': standings})


@blueprint.route('/challenges/<id>/leaderboard', methods=['GET'])
def challenge(id):
    challenge = Challenge.query.get_or_404(id)
    endtime   = current_app.config.get('END_TIME')
    if endtime and endtime <= now():
        official = (request.args.get('scores') == 'official')
        if not official: endtime = None
    else:
        official = None

    teams = scores(end=endtime, challenge_id=id)
    return render_template('scores/challenge.html', teams=teams, official=official, challenge=challenge)

app/web/users/routes.py
import datetime

from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user

from ...lib.models  import db, Account, UserFollowup, UserInfo
from ...lib.require import require
from ...lib.scoring import user_solves
from ...lib.timing  import now

from .forms import NewUserForm, UserFollowupForm, UserInfoForm

blueprint = Blueprint('users', __name__)

@blueprint.route('/users', methods=['GET'])
def index():
    team  = db.aliased(Account)
    users = Account.query.filter_by(user=True)
    if not current_user.is_admin():
        users = users.filter_by(hidden=False, banned=False)
    users = users.join(Account.team.of_type(team), isouter=True).order_by(Account.name)
    return render_template('users/index.html', users=users.all())


@blueprint.route('/users/info', methods=['GET', 'POST'])
@require(user=True)
def info():
    if current_user.info_id is not None:
        flash('You already filled that out.')
        return redirect(url_for('challenges.index'))

    form = UserInfoForm()
    if form.validate_on_submit():
        current_user.info = UserInfo.from_form(form)
        db.session.add(current_user.info)
        db.session.add(current_user)
        db.session.commit()

        flash('Thank you for helping out!')
        return redirect(url_for('challenges.index'))

    return render_template('users/info.html', form=form)


# @blueprint.route('/users/followup', methods=['GET', 'POST'])
@require(user=True)
def followup():
    if current_user.followup_id is not None:
        flash('You already filled that out.')
        return redirect(url_for('challenges.index'))

    form = UserFollowupForm()
    if form.validate_on_submit():
        current_user.followup = UserFollowup.from_form(form)
        db.session.add(current_user.followup)
        db.session.add(current_user)
        db.session.commit()

        flash('Thanks for the feedback!')
        return redirect(url_for('challenges.index'))

    return render_template('users/followup.html', form=form)


@blueprint.route('/users/new', methods=['GET', 'POST'])
@require(user=False)
def new():
    form = NewUserForm()
    if form.validate_on_submit():
        user = Account.from_form(form, include=['password'], ignore=['disclaimer'])
        user.created_at = now()
        user.user = True
        if not Account.query.count():
            user.admin  = True
            user.hidden = True
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash('Welcome to the game!')
        # return redirect(url_for('challenges.index'))
        return redirect(url_for('users.info'))

    return render_template('users/new.html', form=form)


@blueprint.route('/users/<id>', methods=['GET'])
def show(id):
    user = Account.query.filter_by(id=id, user=True).first_or_404()
    return render_template('users/show.html', user=user, solves=user_solves(id))

app/templates/challenges/edit.html
{% extends "layout.html" %}

{% block content %}
<h1>{{ challenge.name }}</h1>

<form method="POST">
  {{ form.csrf_token }}
  {{ form | field('name') }}
  {{ form | field('value') }}
  {{ form | field('language')}}
  {{ form | field('functions')}}
  {{ form | field('hidden')}}

  <fieldset>
    <legend>Sandboxing</legend>
    {{ form | field('container')}}
    {{ form | field('builder')}}
    {{ form | field('tester')}}
  </fieldset>

  <fieldset>
    <legend>Challenge Files</legend>
    {{ form | field('folder')  }}
    {{ form | field('binary')  }}
    {{ form | field('disasm')  }}
    {{ form | field('deccode') }}
    {{ form | field('decomp')  }}
  </fieldset>

  {{ form | field('binja_url') }}

  <div class="buttons">
    <a href="{{ url_for('challenges.index') }}">Cancel</a>
    <input type="submit" value="Save" />
  </div>
</form>
{% endblock %}

app/templates/challenges/editor.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/static/icon.png" />
    <script type="text/javascript" src="/static/ext/ace/ace.js"></script>
    <script type="text/javascript" src="/static/ext/diff-match-patch.js"></script>
    <script type="text/javascript" src="/static/challenges/editor/buttons.js"></script>
    <script type="text/javascript" src="/static/challenges/editor/editors.js"></script>
    <script type="text/javascript" src="/static/challenges/editor/notices.js"></script>
    <script type="text/javascript" src="/static/challenges/editor/replace.js"></script>
    <script type="text/javascript" src="/static/challenges/editor/scoring.js"></script>
    <script type="text/javascript" src="/static/challenges/editor/sharing.js"></script>
    <script type="text/javascript" src="/static/challenges/editor/windows.js"></script>
    <link rel="stylesheet" href="/static/challenges/editor.css" />
    <title>{{ challenge.name }}</title>
    <script type="text/javascript">
      const target    = {{ target  | tojson }};
      const decompile = {{ decompile | tojson }};
      const language  = {{ challenge.language | tojson }};
      var   candidate = null;
      var   parent    = {{ parent }};
    </script>
  </head>
  <body>
    <header>
      <h1>
        <img src="{{ url_for('static', filename='icon.png') }}" />
        <a href="{{ url_for('root') }}">decompiling competition</a> »
        <a href="{{ url_for('challenges.index') }}">challenges</a> »
        {{ challenge.language }} »
        {{ challenge.name }}
      </h1>
      <div id="tabs">
        <a href="{{ url_for('challenges.download', id=challenge.id) }}" download="{{ challenge.name }}">
          <img style="width:16px" src="/static/icons/download.svg" title="Download Binary" />
        </a>
        <span id="comp-tab">Console</span>
        <span id="diff-tab" class="active">ASM (<span id="score-ins">-?</span>/<span id="score-del">+?</span>)</span>
        <span id="score-tab">Score (<span id="score-pct">?%</span>)</span>
      </div>
    </header>
    <content>
      <div id="verso">
        <div id="code-edit" class="panel">{{ decomp }}</div>
        <div id="buttons">
          <div id="sharing-btn" class="button secondary">
            <span title="Shortcut: ^O">Load</span>
          </div>
          <div id="replace-btn" class="button secondary">
            <span title="Shortcut: ^H">Replace</span>
          </div>
{% if options %}
          <div id="options-btn" class="button secondary">Options</div>
{% endif %}
          <div id="do-compile" class="button">
            <span title="Shortcut: ^Enter">Compile</span>
          </div>
        </div>
      </div>
      <div id="recto">
        <div id="note-view" class="panel">; This is the disassembly you're trying to reproduce.
; It uses Intel syntax (mov dst, src).

; You can make notes in this pane for reference,
; but they won't be saved if you leave the page.

{{ target }}</div>
        <div id="comp-view" class="panel">Compile to see compiler output.</div>
        <div id="diff-view" class="panel active">
          <div id="asm-opts" class="view-options">
            <select id="asm-function"></select>
            <span id="asm-mode" class="toggle">
              <label><input type="radio" name="asm-view" value="target" checked="" />Target</label>
              <label><input type="radio" name="asm-view" value="decompile" checked="" />Decompiler</label>
              <label><input type="radio" name="asm-view" value="candidate" />Candidate</label>
              <label><input type="radio" name="asm-view" value="diff" />Diff</label>
            </span>
            <a id="find-btn">Find</a>
            <span class="toggle">
              <span id="replace-text"><input type="checkbox" id="replace-check" />Replace</span>
            </span>
          </div>
          <div id="asm-edit">; Compile to see the disassembly diff.</div>
        </div>
        <div id="score-view" class="panel">
          <table>
            <thead>
              <tr>
                <td>Source</td>
                <td></td>
                <td>Score</td>
                <td>Weight</td>
                <td>Total</td>
              </tr>
            </thead>
            <tbody id="score-table">
              <tr>
                <td>Test Cases</td>
                <td></td>
                <td>?%</td>
                <td>20%</td>
                <td>?%</td>
              </tr>
              <tr>
                <td>ASM Diff</td>
                <td></td>
                <td>?%</td>
                <td>60%</td>
                <td>?%</td>
              </tr>
              <tr>
                <td colspan="2">Perfect Match Bonus</td>
                <td>?%</td>
                <td>20%</td>
                <td>?%</td>
              </tr>
              <tr>
                <td colspan="2">Latest Submission</td>
                <td></td>
                <td></td>
                <td>?%</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </content>

    <div id="screen" style="display:none"></div>

    <div id="spinner-win" class="window center">
      Loading...
    </div>

{% if options %}
    <div id="options-win" class="window center">
      <p>Configure your compile here.  Add one compile flag per line.  Use an equals sign to set options that reguire arguments, for example: <tt>-march=mips</tt></p>
      <div id=options-list>
        <div id="options-template"><img class="x" src="/static/remove.svg" title="Remove" /><input type="text" required pattern="-.*" /></div>
      </div>
      <div id="options-add"  class="button secondary">Add Option</div>
      <div id="options-done" class="button">Done</div>
    </div>
{% endif %}

    <div id="replacement-win" class="window center">
      <p>Specify replacements here.  These will be applied before the diff.  This won't improve your score, but it can be used to make the diff much easier to read.</p>
      <div id="replacement-wrapper">
        <table>
          <tbody style="display:none">
            <tr id="replacement-template">
              <td>Replace</td>
              <td><input type="text" /></td>
              <td>in</td>
              <td>
                <select>
                  <option value="target">Target</option>
                  <option value="decompile">Decompiler</option>
                  <option value="candidate">Candidate</option>
                </select>
              </td>
              <td>with</td>
              <td><input type="text" /></td>
              <td><img class="x" src="/static/icons/remove.svg" title="Remove" /></td>
            </tr>
          </tbody>
          <tbody id="replacements">
          </tbody>
        </table>
      </div>
      <div id="replacement-add"  class="button secondary">Add Replacement</div>
      <div id="replacement-done" class="button cancel-btn">Done</div>
    </div>

    <div id="sharing-win" class="window center">
      <form>
        <table style="width:100%">
          <thead>
            <tr>
              <th><input type="radio" style="visibility: hidden" /> Author</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody id="sharing-tbl"></tbody>
        </table>

        <div class="small-buttons">
          <div class="button cancel-btn secondary">Cancel</div>
          <input type="submit" id="do-sharing" class="button" value="Load" />
        </div>
      </form>
    </div>

    <div id="find-win" class="window left">
      <form>
        <label>
          <div>Find</div>
          <input type="text" id="find-src" />
        </label>
        <div class="small-buttons">
          <div class="button cancel-btn secondary">Close</div>
          <div class="button secondary" id="do-find-prev">Prev</div>
          <input type="submit" id="do-find-next" class="button" value="Next" />
        </div>
      </form>
    </div>

    <div id="replace-win" class="window center">
      <form>
        <label>
          <div>Find</div>
          <input type="text" id="replace-src" />
        </label>
        <label>
          <div>Replace With</div>
          <input type="text" id="replace-dst" />
        </label>
        <div class="small-buttons">
          <div class="button cancel-btn secondary">Cancel</div>
          <input type="submit" id="do-replace" class="button" value="Replace" />
        </div>
      </form>
    </div>

    <div id="error-win" class="window center">
      <p>Something went wrong.</p>
      <p>You can try again if you'd like, but this probably means there's something wrong with the server.</p>
      <div class="button cancel-btn">Hmmm...</div>
    </div>

    <div id="finished-win" class="window center">
      <p>The competition is over!  No more source code submissions will be accepted.</p>
      <p>You can head over to the <a href="{{ url_for('scores.html') }}">scoreboard</a> to see the final scores, or you can keep looking at this challenge.</p>
      <div class="button cancel-btn">Keep Looking</div>
    </div>

    <script type="text/javascript">
      window.onload = function() {
        editors.init()
        buttons.init()
      }
    </script>
  </body>
</html>

app/templates/challenges/index.html
{% extends "layout.html" %}

{% block style %}
tr :nth-child(1) {text-align: left;}
tr :nth-child(2) {text-align: left;}
tr :nth-child(3) {text-align: center;}
tr :nth-child(4) {text-align: right;}
tr :nth-child(5) {text-align: right;}
{% endblock %}

{% block content %}
<h1>Challenges</h1>

{% if current_user.is_admin() %}
<div class="subhead">
  <a href="{{ url_for('challenges.new') }}">New Challenge</a> &bull;
  <a href="{{ url_for('challenges.upload') }}">Bulk Upload</a>
</div>
{% endif %}

{% if not current_user.get_id() %}
<p class="subsubhead">You'll need to <a href="{{ url_for('login.login') }}">log in</a>
or <a href="{{ url_for('users.new') }}">register</a>
before you can access the challenges.</p>
{% endif %}

<table>
  <thead>
    <tr>
      <th>Challenge</th>
      <th>Lang.</th>
      <th>Value</th>
      <th>Score</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
{% for challenge in challenges %}
    <tr>
      <td>
        <a href="{{ url_for('challenges.show', id=challenge.id) }}">{{ challenge.name }}</a>
        <span class="id">#{{ challenge.id }}</span>
        {{ "(hidden)" if challenge.hidden }}
      </td>
      <td>{{ challenge.language }}</td>
      <td>{{ challenge.value }}</td>
      <td>{{ solves.get(challenge.id) | percent }}</td>
      <td>
        <a href="{{ url_for('scores.challenge', id=challenge.id) }}"><img width="16px" src="/static/icons/trophy.svg" title="Leaderboard" /></a>
        <a href="{{ url_for('challenges.download', id=challenge.id) }}" download="{{ challenge.name }}"><img width="16px" src="/static/icons/download.svg" title="Download Binary" /></a>
{% if current_user.is_admin() %}
        <a href="{{ url_for('challenges.edit', id=challenge.id) }}"><img width="16px" src="/static/icons/edit.svg" title="Edit" /></a>
        <a href="{{ url_for('challenges.delete', id=challenge.id) }}"><img width="16px" src="/static/icons/delete.svg" title="Delete" /></a>
{% endif %}
      </td>
    </tr>
{% endfor %}
{% if not challenges %}
    <tr class="placeholder">
      <td colspan="999">challenges will appear when the competition starts</td>
    </tr>
{% endif %}
  </tbody>
</table>
{% endblock %}

app/templates/challenges/new.html
{% extends "layout.html" %}

{% block content %}
<h1>New Challenge</h1>

<form method="POST">
  {{ form.csrf_token }}
  {{ form | field('name') }}
  {{ form | field('value') }}
  {{ form | field('language')}}
  {{ form | field('functions')}}
  {{ form | field('hidden')}}

  <fieldset>
    <legend>Sandboxing</legend>
    {{ form | field('container')}}
    {{ form | field('builder')}}
    {{ form | field('tester')}}
  </fieldset>

  <fieldset>
    <legend>Challenge Files</legend>
    {{ form | field('folder') }}
    {{ form | field('binary') }}
    {{ form | field('disasm') }}
    {{ form | field('decomp') }}
  </fieldset>
  <div class="buttons">
    <a href="{{ url_for('challenges.upload') }}">Bulk Upload</a>
    <input type="submit" value="Create" />
  </div>
</form>
{% endblock %}

app/templates/challenges/upload.html
{% extends "layout.html" %}

{% block content %}
<h1>Upload Challenges</h1>

<form method="POST" enctype="multipart/form-data">
  {{ form.csrf_token }}
  {{ form | field('config_path') }}
  <div class="buttons">
    <a href="{{ url_for('challenges.new') }}">New Challenge</a>
    <input type="submit" value="Upload" />
  </div>
</form>
{% endblock %}