app/web/teams/forms.py
from flask_wtf import FlaskForm
from functools import cached_property
from wtforms import PasswordField, SelectField, StringField
from wtforms.validators import InputRequired, Length, ValidationError

from ...lib.models import Account

class TeamForm(FlaskForm):
    name = StringField('Team Name',
        description = 'All user and team names must be unique.',
        validators  = [InputRequired()]
    )

    password = PasswordField('Team Password',
        description = 'Anyone who knows this password will be able to join the team.',
        validators  = [InputRequired()]
    )

    # email = StringField('Email Address',
    #     widget      =  EmailInput(),
    #     validators  = [InputRequired()],
    #     description = (
    #         'This will be used during the competition (if '
    #         'necessary) and to send out final results.'
    #     )
    # )

    def validate_name(self, field):
        if Account.query.filter_by(name=field.data).first():
            raise ValidationError('This name is already taken.')


class TeamJoinForm(FlaskForm):
    team_id = SelectField('Team', choices=[], coerce=int, validators = [
        InputRequired()
    ], validate_choice=False)

    password = PasswordField('Password', validators = [
        InputRequired()
    ])

    @cached_property
    def team(self):
        return Account.query.filter_by(id=self.team_id.data, user=False).first()

    def validate_team_id(self, field):
        if not self.team:
            raise ValidationError('No such team.')

    def validate_password(self, field):
        if self.team and not self.team.check_password(field.data):
            raise ValidationError('Incorrect password.')


class TeamLeaveForm(FlaskForm):
    pass

app/web/teams/routes.py
import datetime
import json

from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user

from ...lib.models  import db, Account
from ...lib.require import require
from ...lib.scoring import solves
from ...lib.timing  import now

from .forms import TeamForm, TeamJoinForm, TeamLeaveForm

blueprint = Blueprint('teams', __name__)

@blueprint.route('/teams', methods=['GET'])
def index():
    teams = Account.query.filter_by(user=False).order_by(Account.name).all()
    return render_template('teams/index.html', teams=teams)


@blueprint.route('/teams/new', methods=['GET', 'POST'])
@require(team=False)
def new():
    form = TeamForm()
    if form.validate_on_submit():
        team = Account.from_form(form, include=['password'])
        team.created_at = now()
        team.user = False
        current_user.team = team
        db.session.add(current_user)
        db.session.add(team)
        db.session.commit()

        flash('Team created.')
        return redirect(url_for('teams.show', id=team.id))

    return render_template('teams/new.html', form=form)


@blueprint.route('/teams/join', methods=['GET', 'POST'])
@require(team=False)
def join():
    form = TeamJoinForm()
    if form.validate_on_submit():
        current_user.team_id = form.team.id
        current_user.captain = False
        db.session.add(current_user)
        db.session.commit()

        flash('Welcome to the team!')
        return redirect(url_for('teams.show', id=current_user.team_id))

    teams = Account.query.filter_by(user=False).order_by('name').all()
    if not teams:
        flash('No teams exist yet, but you can create one.')
        return redirect(url_for('teams.new'))

    form.team_id.choices = [(t.id, t.name) for t in teams]
    return render_template('teams/join.html', form=form)


@blueprint.route('/teams/leave', methods=['GET', 'POST'])
@require(team=True)
def leave():
    form = TeamLeaveForm()
    if form.validate_on_submit():
        current_user.team_id = None
        db.session.add(current_user)
        db.session.commit()

        flash('You have left the team.')
        return redirect(url_for('users.show', id=current_user.id))

    team = current_user.team
    return render_template('teams/leave.html', team=team, form=form)


@blueprint.route('/teams/<id>', methods=['GET'])
def show(id):
    team = Account.query.filter_by(id=id, user=False).first_or_404()
    return render_template('teams/show.html', team=team, solves=solves(id))

app/web/teams/templates/index.html
{% extends "layout.html" %}

{% block content %}
<h1>Teams</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
    </tr>
  </thead>
  <tbody>
{% for team in teams %}
    <tr>
      <td>
        <img width="16px" src="/static/icons/team.svg" title="Team" />
        <a href="{{ url_for('teams.show', id=team.id) }}">{{ team.name }}</a>
        <span class="id">#{{ team.id }}</span>
      </td>
    </tr>
{% endfor %}
{% if not teams %}
    <tr class="placeholder">
      <td colspan="999">no teams yet</td>
    </tr>
{% endif %}

  </tbody>
</table>
{% endblock %}

app/web/teams/templates/join.html
{% extends "layout.html" %}

{% block content %}
<h1>Join Team</h1>
<p class="subsubhead">Unlike last year, you don't have to join a team to play!</p>

<form action="{{ url_for('teams.join') }}" method="POST">
  {{ form.csrf_token }}
  {{ form | field('team_id') }}
  {{ form | field('password') }}
  <div class="buttons">
    <a href="{{ url_for('teams.new') }}">New Team</a>
    <input type="submit" value="Join" />
  </div>
</form>
{% endblock %}

app/web/teams/templates/leave.html
{% extends "layout.html" %}

{% block content %}
<h1>Leave Team</h1>

<form action="{{ url_for('teams.leave') }}" method="POST">
  {{ form.csrf_token }}
  <p>Are you sure you want to leave {{ team.name }}?  Any challenges you've
  submitted for the team will remain credited to them, but you'll be free to
  play solo or join a different team.  You'll need to know the team password
  of any team you want to join.</p>
  <div class="buttons">
    <a href="{{ url_for('teams.show', id=team.id) }}">Cancel</a>
    <input type="submit" value="Leave" />
  </div>
</form>
{% endblock %}

app/web/teams/templates/new.html
{% extends "layout.html" %}

{% block content %}
<h1>New Team</h1>
<p class="subsubhead">Unlike last year, you don't have to join a team to play!</p>


<form action="{{ url_for('teams.new') }}" method="POST">
  {{ form.csrf_token }}
  {{ form | field('name') }}
  {{ form | field('password') }}
  {# form | field('email') #}
  <div class="buttons">
    <a href="{{ url_for('teams.join') }}">Join Team</a>
    <input type="submit" value="Create" />
  </div>
</form>
{% endblock %}

app/web/teams/templates/show.html
{% extends "layout.html" %}

{% block style %}
td:nth-child(3) {text-align: center;}
td:nth-child(4) {text-align: right;}
td:nth-child(5) {text-align: right;}
{% endblock %}

{% block content %}
<h1>{{ team.name }}</h1>
{% if team.members | length == 1 %}
<div class="subhead">1 member</div>
{% else %}
<div class="subhead">{{ team.members | length }} members</div>
{% endif %}

<table>
  <thead>
    <tr>
      <th>Users</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
{% for user in team.members %}
    <tr>
      <td>
        <img width="16px" src="/static/icons/user.svg" title="User" />
        <a href="{{ url_for('users.show', id=user.id) }}">{{ user.name }}</a>
        <span class="id">#{{ user.id }}</span>
      </td>
      <td>
{% if user.get_id() == current_user.get_id() %}
        <a href="{{ url_for('teams.leave') }}">Leave</a>
{% endif %}
      </td>
    </tr>
{% endfor %}
{% if not team.members %}
    <tr class="placeholder">
      <td colspan="999">no members</td>
    </tr>
{% endif %}
  </tbody>
</table>

{% include "solves.html" %}
{% endblock %}