app/web/login/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for
import flask_login

from .forms import LoginForm

blueprint = Blueprint('login', __name__)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        flask_login.login_user(form.user)
        if not form.user.info_id:
            return redirect(url_for('users.info'))
        return redirect(url_for('challenges.index'))
    return render_template('login/login.html', form=form)


@blueprint.route('/logout', methods=['POST'])
def logout():
    flask_login.logout_user()
    flash('You have been logged out.')
    return redirect(url_for('login.login'))

app/web/scores/routes.py
from flask import Blueprint, current_app, jsonify, render_template, request
import datetime

from ...lib.models  import Challenge
from ...lib.scoring import firsts, scores
from ...lib.timing  import now

blueprint = Blueprint('scores', __name__)


@blueprint.route('/scoreboard', methods=['GET'])
def html():
    endtime = current_app.config.get('END_TIME')
    if endtime and endtime <= now():
        official = (request.args.get('scores') == 'official')
        if not official: endtime = None
    else:
        official = None

    teams = scores(end=endtime)
    return render_template('scores/scoreboard.html', teams=teams, official=official)


@blueprint.route('/firstblood', methods=['GET'])
def firstblood():
    return render_template('scores/firstblood.html', submissions=firsts())


@blueprint.route('/scoreboard.json', methods=['GET'])
def json():
    endtime   = current_app.config.get('END_TIME')
    standings = []

    for team in scores(end=endtime):
        standings.append({
            'team':  team.name,
            'score': round(team.score, 2),
            'pos':   team.rank
        })

    return jsonify({'standings': standings})


@blueprint.route('/challenges/<id>/leaderboard', methods=['GET'])
def challenge(id):
    challenge = Challenge.query.get_or_404(id)
    endtime   = current_app.config.get('END_TIME')
    if endtime and endtime <= now():
        official = (request.args.get('scores') == 'official')
        if not official: endtime = None
    else:
        official = None

    teams = scores(end=endtime, challenge_id=id)
    return render_template('scores/challenge.html', teams=teams, official=official, challenge=challenge)

app/web/teams/routes.py
import datetime
import json

from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user

from ...lib.models  import db, Account
from ...lib.require import require
from ...lib.scoring import solves
from ...lib.timing  import now

from .forms import TeamForm, TeamJoinForm, TeamLeaveForm

blueprint = Blueprint('teams', __name__)

@blueprint.route('/teams', methods=['GET'])
def index():
    teams = Account.query.filter_by(user=False).order_by(Account.name).all()
    return render_template('teams/index.html', teams=teams)


@blueprint.route('/teams/new', methods=['GET', 'POST'])
@require(team=False)
def new():
    form = TeamForm()
    if form.validate_on_submit():
        team = Account.from_form(form, include=['password'])
        team.created_at = now()
        team.user = False
        current_user.team = team
        db.session.add(current_user)
        db.session.add(team)
        db.session.commit()

        flash('Team created.')
        return redirect(url_for('teams.show', id=team.id))

    return render_template('teams/new.html', form=form)


@blueprint.route('/teams/join', methods=['GET', 'POST'])
@require(team=False)
def join():
    form = TeamJoinForm()
    if form.validate_on_submit():
        current_user.team_id = form.team.id
        current_user.captain = False
        db.session.add(current_user)
        db.session.commit()

        flash('Welcome to the team!')
        return redirect(url_for('teams.show', id=current_user.team_id))

    teams = Account.query.filter_by(user=False).order_by('name').all()
    if not teams:
        flash('No teams exist yet, but you can create one.')
        return redirect(url_for('teams.new'))

    form.team_id.choices = [(t.id, t.name) for t in teams]
    return render_template('teams/join.html', form=form)


@blueprint.route('/teams/leave', methods=['GET', 'POST'])
@require(team=True)
def leave():
    form = TeamLeaveForm()
    if form.validate_on_submit():
        current_user.team_id = None
        db.session.add(current_user)
        db.session.commit()

        flash('You have left the team.')
        return redirect(url_for('users.show', id=current_user.id))

    team = current_user.team
    return render_template('teams/leave.html', team=team, form=form)


@blueprint.route('/teams/<id>', methods=['GET'])
def show(id):
    team = Account.query.filter_by(id=id, user=False).first_or_404()
    return render_template('teams/show.html', team=team, solves=solves(id))

app/web/users/routes.py
import datetime

from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user

from ...lib.models  import db, Account, UserFollowup, UserInfo
from ...lib.require import require
from ...lib.scoring import user_solves
from ...lib.timing  import now

from .forms import NewUserForm, UserFollowupForm, UserInfoForm

blueprint = Blueprint('users', __name__)

@blueprint.route('/users', methods=['GET'])
def index():
    team  = db.aliased(Account)
    users = Account.query.filter_by(user=True)
    if not current_user.is_admin():
        users = users.filter_by(hidden=False, banned=False)
    users = users.join(Account.team.of_type(team), isouter=True).order_by(Account.name)
    return render_template('users/index.html', users=users.all())


@blueprint.route('/users/info', methods=['GET', 'POST'])
@require(user=True)
def info():
    if current_user.info_id is not None:
        flash('You already filled that out.')
        return redirect(url_for('challenges.index'))

    form = UserInfoForm()
    if form.validate_on_submit():
        current_user.info = UserInfo.from_form(form)
        db.session.add(current_user.info)
        db.session.add(current_user)
        db.session.commit()

        flash('Thank you for helping out!')
        return redirect(url_for('challenges.index'))

    return render_template('users/info.html', form=form)


# @blueprint.route('/users/followup', methods=['GET', 'POST'])
@require(user=True)
def followup():
    if current_user.followup_id is not None:
        flash('You already filled that out.')
        return redirect(url_for('challenges.index'))

    form = UserFollowupForm()
    if form.validate_on_submit():
        current_user.followup = UserFollowup.from_form(form)
        db.session.add(current_user.followup)
        db.session.add(current_user)
        db.session.commit()

        flash('Thanks for the feedback!')
        return redirect(url_for('challenges.index'))

    return render_template('users/followup.html', form=form)


@blueprint.route('/users/new', methods=['GET', 'POST'])
@require(user=False)
def new():
    form = NewUserForm()
    if form.validate_on_submit():
        user = Account.from_form(form, include=['password'], ignore=['disclaimer'])
        user.created_at = now()
        user.user = True
        if not Account.query.count():
            user.admin  = True
            user.hidden = True
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash('Welcome to the game!')
        # return redirect(url_for('challenges.index'))
        return redirect(url_for('users.info'))

    return render_template('users/new.html', form=form)


@blueprint.route('/users/<id>', methods=['GET'])
def show(id):
    user = Account.query.filter_by(id=id, user=True).first_or_404()
    return render_template('users/show.html', user=user, solves=user_solves(id))

app/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="{{ url_for('static', filename='icon.png') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='decompetition.css') }}" />
    <title>{% block title %}Decompetition{% endblock %}</title>
    <style type="text/css">{% block style %}{% endblock %}</style>
  </head>
  <body>
    <header>
      <div id="nav-right">
{% if current_user.is_authenticated() %}
        <a id="nav-user" href="{{ url_for('users.show', id=current_user.id) }}">{{ current_user.name }}</a> &bull;
{%   if current_user.get_team_id() %}
        <a id="nav-team" href="{{ url_for('teams.show', id=current_user.team.id) }}">{{ current_user.team.name }}</a> &bull;
{%   else %}
        <a id="nav-join" href="{{ url_for('teams.join') }}">join a team</a> &bull;
{%   endif %}
{%   if not current_user.info_id %}
        <a id="nav-info" href="{{ url_for('users.info') }}">user info</a><span id="info-nag">?</span> &bull;
{%   endif %}
{#   if not current_user.followup_id %}
        <a id="nav-info" href="{{ url_for('users.followup') }}">follow-up</a><span id="info-nag">?</span> &bull;
{%   endif #}
{% endif %}
        <a id="nav-discord" target="_blank" href="https://discord.gg/TQ64RP6PZR">discord</a> &bull;
{% if current_user.is_authenticated() %}
        <form id="nav-logout" method="post" action="{{ url_for('login.logout') }}">
          <button type="submit">log out</button>
        </form>
{% else %}
        <a id="nav-login"    href="{{ url_for('login.login') }}">log in</a> &bull;
        <a id="nav-register" href="{{ url_for('users.new') }}">register</a>
{% endif %}
      </div>
      <div id="nav-left">
        <img src="{{ url_for('static', filename='icon.png') }}" />
        <a id="nav-root"   href="{{ url_for('root') }}">decompiling competition</a> &bull;
{% if current_user.is_admin() %}
        <a id="nav-teams"  href="{{ url_for('teams.index') }}">teams</a> &bull;
        <a id="nav-users"  href="{{ url_for('users.index') }}">users</a> &bull;
{% endif %}
        <a id="nav-chals"  href="{{ url_for('challenges.index') }}">challenges</a> &bull;
        <a id="nav-scores" href="{{ url_for('scores.html') }}">scoreboard</a>
      </div>
    </header>
    <content>
{% block content %}
{% endblock %}
    </content>
    <div id="messages">
{% for category, message in get_flashed_messages(with_categories=True) %}
      <div class="{{ category }}">{{ message }}</div>
{% endfor %}
    </div>
  </body>
</html>

app/templates/main.html
{% extends "layout.html" %}

{% block style %}
#signup {
  border: 4pt solid #aa77ff;
  border-radius: 1em;
  display: block;
  font-size: x-large;
  margin: 1.5em auto;
  padding: 1em;
  text-align: center;
  text-decoration: none;
  width: 1.5in;
}

#signup:hover {
  background-color: #000000;
}

h2 {
  color: #AD1E00;
  font-size: larger;
  margin: 2em auto -6pt auto;
}

h1 + h2 {
  margin-top: unset;
}
{% endblock %}

{% block content %}
<img id="hero" src="/static/logo.png" />
<h1>Decompiling Competition</h1>
<!-- 
<div class="subhead">
  Congratulations to <a href="{{ url_for('teams.show', id=17) }}">PPP</a> for taking first place!
</div>
-->

<p>Calling all reverse engineers! Test your reversing skills against the systems
languages of the twenty-first century: C, C++, Go, Rust, and Swift. Given only a
binary, can you recreate the original source code?</p>

{% if not current_user.get_id() %}
<a id="signup" class="button" href="{{ url_for('users.new') }}">Sign Up!</a>
{% endif %}

<p>Your candidate source code will be compiled, and the resulting binary will be
tested and disassembled.  The majority of your score will come from the
<a href="https://en.wikipedia.org/wiki/Jaccard_index">intersection over union</a>
of your disassembly versus the target disassembly.  How close can you get to a
perfect reconstruction?</p>


<h1 style="margin-top: 0.75in">The Details</h1>

<h2>Playing</h2>
<p>Anyone with an internet connection and a web browser can play.  Access to a
reverse engineering program may be helpful, but isn't required.  If you don't
have any reversing software locally, check out
<a href="https://cloud.binary.ninja/">Binary Ninja Cloud</a>.</p>

<p>This is a team competition. There's no team size limit.</p>


<h2>Scoring</h2>
<p>Your candidate source code will be compiled, and the resulting binary will be
tested and disassembled. Your score on any challenge is made up of:</p>
<ul>
  <li><strong>20%</strong> unit tests.  Pass (hidden) test cases to get these points.</li>
  <li><strong>60%</strong> binary diff.  Match the target disassembly to get these points. </li>
  <li><strong>20%</strong> perfect match.  Bonus points for a perfect binary match.</li>
</ul>

<p>The test case points and the binary diff points can be partial&mdash;you'll
get more and more points as you improve your source code&mdash;but the final
20% bonus for a perfect match is all-or-nothing.</p>


<h2>Prizes</h2>
<p>The top three teams will win themselves some Amazon gift cards.  In the case
of a tie, prizes will be combined and split evenly.  All prizes are in USD:</p>

<ul>
  <li><strong>$5</strong> for first place.</li>
  <li><strong>$3</strong> for second place.</li>
  <li><strong>$2</strong> for third place.</li>
</ul>


<h2>Environment</h2>
<p>All challenges were built for x86-64 and run on Ubuntu 20.04.  The builder
container is named <code>decompetition/builder-2021</code> and is available on
<a href="https://hub.docker.com/r/decompetition/builder-2021">DockerHub</a>.
Compilers are:</p>

<ul>
  <li><code>gcc 9.3.0</code></li>
  <!-- 
  <li><code>g++ 9.3.0 -std=c++17</code></li>
  <li><code>go 1.13.8</code></li>
  <li><code>nim 1.0.6</code></li>
  <li><code>rustc 1.53.0</code></li>
  <li><code>swiftc 5.5.2</code></li>
  -->
</ul>


<h2>Disclaimer</h2>
<p>Decompetition is part of a research project on the process of reverse
engineering.  Our research is mainly exploratory:</p>

<ul>
  <li>We're interested in following the full reversing process,
  to see how reversers work as they go from nothing to fully
  equivalent source code with the help of decompilers.</li>
  <li>We're interested to see how effective the current SOTA decompiler is 
  and how much it can help reverse engineers understand the code.</li>
</ul>

<p>We'll record your source code submissions so we can follow the
reversing process.  So don't upload any private information in your source.
Not that you were going to do that, right?</p>
{% endblock %}

app/templates/solves.html
<table>
  <thead>
    <th>Challenge</th>
    <th>Lang.</th>
    <th>Value</th>
    <th>Best</th>
    <th>Latest</th>
  </thead>
  <tbody>
{% for solve in solves %}
    <tr>
      <td>
        <a href="{{ url_for('challenges.show', id=solve.id) }}">{{ solve.name }}</a>
        <span class="id">#{{ solve.id }}</span>
      </td>
      <td>{{ solve.language }}</td>
      <td>{{ solve.possible }}</td>
      <td>{{ solve.score | percent }}</td>
      <td>{{ solve.created_at | datetime }}</td>
    </tr>
{% endfor %}
{% if not solves %}
    <tr class="placeholder">
      <td colspan="999">no submissions</td>
    </tr>
{% endif %}
  </tbody>
</table>