app/web/challenges/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, IntegerField, SelectField, StringField
from wtforms.validators import DataRequired, InputRequired, NumberRange, Optional, ValidationError

import os

class LocalDirRequired:
    def __init__(self, message='Directory does not exist.'):
        self.message = message

    def __call__(self, form, field):
        if not os.path.isdir(field.data):
            raise ValidationError(self.message)

class LocalFileRequired:
    def __init__(self, message='File does not exist.'):
        self.message = message

    def __call__(self, form, field):
        if not os.path.isfile(field.data):
            raise ValidationError(self.message)

LANGUAGES = [
    ('c',     'C'),
    ('cpp',   'C++'),
    ('go',    'Go'),
    ('nim',   'Nim'),
    ('rust',  'Rust'),
    ('swift', 'Swift')
]

class ChallengeForm(FlaskForm):
    name = StringField('Name',  validators = [
        DataRequired()
    ])

    value = IntegerField('Value', validators = [
        DataRequired(),
        NumberRange(min=0)
    ])

    language = SelectField('Language', choices=LANGUAGES, validators = [
        DataRequired()
    ])

    functions = StringField('Functions', validators = [
        DataRequired()
    ])

    hidden = BooleanField('Hidden', default=False)

    container = StringField('Container', validators = [
        DataRequired()
    ])

    builder = StringField('Path to Build Script', validators = [
        DataRequired(),
        LocalFileRequired()
    ])

    tester = StringField('Path to Test Script', validators = [
        DataRequired(),
        LocalFileRequired()
    ])

    folder = StringField('Path to Challenge Folder', validators = [
        DataRequired(),
        LocalDirRequired()
    ])

    binary = StringField('Path to Binary', validators = [
        DataRequired(),
        LocalFileRequired()
    ])

    disasm = StringField('Path to Disassembly', validators = [
        Optional(),
        LocalFileRequired()
    ])

    deccode = StringField('Path to Decompiler results', validators = [
        Optional(),
        LocalFileRequired()
    ])

    decomp = StringField('Path to Starter Code', validators = [
        DataRequired(),
        LocalFileRequired()
    ])

    binja_url = StringField('Binary Ninja Cloud URL', validators = [
        Optional()
    ])

    @staticmethod
    def from_challenge_info(info):
        return ChallengeForm(
            name      = info.name,
            value     = info.value,
            language  = info.language,

            functions = ' '.join(info.functions),
            container = info.container,
            builder   = info.builder,
            tester    = info.tester,

            folder    = info.folder,
            # source    = info.source,
            decomp    = info.starter,
            binary    = info.binary,
            disasm    = info.disasm,
            deccode   = info.deccode
        )


class ChallengeUploadForm(FlaskForm):
    config_path = StringField('Config File',
        description = 'Path to a config file on the app server.',
        validators  = [
            InputRequired(),
            LocalFileRequired()
        ]
    )

app/web/challenges/routes.py
from flask import Blueprint, current_app, flash, redirect, render_template, request, send_file, url_for
from flask_login import current_user
from .forms import ChallengeForm, ChallengeUploadForm

from ...lib.challs  import ChallengeImpl
from ...lib.differ  import diff_all
from ...lib.models  import db, Account, Challenge, Submission
from ...lib.require import require
from ...lib.scoring import solves
from ...lib.timing  import now

import datetime
import json
import os
import yaml

def readfile(path):
    with open(path) as file:
        return file.read()

blueprint = Blueprint('challenges', __name__)

@blueprint.route('/challenges', methods=['GET'])
def index():
    begtime = current_app.config.get('START_TIME')
    if not current_user.is_admin() and begtime and begtime > now():
        challenges = []
        scoremap   = {}
    else:
        challenges = Challenge.query.order_by('name')
        if not current_user.is_admin():
            challenges = challenges.filter_by(hidden=False)
        challenges = challenges.all()
        scoremap   = {s.id:s.score for s in solves(current_user.get_owner_id())}
    return render_template('challenges/index.html', challenges=challenges, solves=scoremap)


@blueprint.route('/challenges/new', methods=['GET', 'POST'])
@require(admin=True)
def new():
    form = ChallengeForm()
    if form.validate_on_submit():
        challenge = Challenge.from_form(form)
        db.session.add(challenge)
        db.session.commit()
        flash('Challenge created.')
        return redirect(url_for('challenges.index'))
    return render_template('challenges/new.html', form=form)


@blueprint.route('/challenges/upload', methods=['GET', 'POST'])
@require(admin=True)
def upload():
    upload_form = ChallengeUploadForm()
    if upload_form.validate_on_submit():
        from ...lib.challs import load
        infos = load(upload_form.config_path.data)

        for info in infos:
            form = ChallengeForm.from_challenge_info(info)
            if not form.validate():
                db.session.rollback()
                return render_template('challenges/new.html', form=form)
            challenge = Challenge.from_form(form)
            db.session.add(challenge)
        db.session.commit()
        flash('Upload successful.')
        return redirect(url_for('challenges.index'))
    return render_template('challenges/upload.html', form=upload_form)


@blueprint.route('/challenges/<id>', methods=['GET'])
@require(user=True, running=True)
def show(id):
    challenge  = Challenge.query.get_or_404(id)
    submission = Submission.query.filter_by(
        user_id      = current_user.get_id(),
        challenge_id = challenge.id
    ).order_by(
        Submission.id.desc()
    ).first()

    if submission:
        decomp = submission.submission
        parent = submission.id
    else:
        decomp = readfile(challenge.decomp)
        parent = 0

    with open(challenge.disasm) as file:
        target = yaml.safe_load(file)

    with open(challenge.deccode) as file:
        decompile = yaml.safe_load(file)

    return render_template('challenges/editor.html',
        challenge = challenge,
        target    = target,
        decompile = decompile,
        decomp    = decomp,
        parent    = parent
    )


@blueprint.route('/challenges/<id>', methods=['POST'])
@require(user=True, running=True)
def compile(id):
    # endtime = current_app.config.get('END_TIME')
    # if endtime and endtime <= now():
    #     return 'The competition has ended.', 403

    challenge  = Challenge.query.get_or_404(id)
    submission = Submission(
        challenge  = challenge,
        user_id    = current_user.get_id(),
        owner_id   = current_user.get_owner_id(),
        ip_address = request.remote_addr,
        submission = request.form['source'],
        parent_id  = request.form.get('parent'),
        created_at = now()
    )

    os.makedirs(submission.folder, exist_ok=True)
    with open(submission.source, 'w') as file:
        file.write(submission.submission)

    build = submission.compile()
    if build.returncode != 0:
        submission.test_score = 0.0
        submission.diff_score = 0.0
        submission.diff_bonus = 0.0
        submission.score      = 0.0
        if not current_user.is_admin():
            db.session.add(submission)
            db.session.commit()

        return json.dumps({
            'id':     submission.id,
            'stdout': build.stdout
        })

    disasm = submission.disassemble()
    with open(challenge.disasm) as file:
        target = yaml.safe_load(file)
    hunks, delta = diff_all(disasm, target)
    tests = submission.test()

    submission.test_score = tests['pass'] / tests['total']
    submission.diff_score = delta[1]      / delta[3]
    submission.diff_bonus = 1.0 if submission.diff_score == 1.0 else 0.0
    submission.score      = sum([
        0.2 * submission.test_score,
        0.6 * submission.diff_score,
        0.2 * submission.diff_bonus
    ])

    if not current_user.is_admin():
        db.session.add(submission)
        db.session.commit()

    return json.dumps({
        'id':        submission.id,
        'stdout':    build.stdout,
        'functions': hunks,
        'scores':    {
            'ins':   delta[0],
            'del':   delta[2],
            'tests': submission.test_score,
            'diffs': submission.diff_score,
            'bonus': submission.diff_bonus,
            'total': submission.score
        }
    })


@blueprint.route('/challenges/<id>/download', methods=['GET'])
@require(user=True)
def download(id):
    begtime = current_app.config.get('START_TIME')
    if begtime and begtime > now():
        flash('The competition hasn\'t started yet.', 'warning')
        return redirect(url_for('challenges.index'))

    challenge = Challenge.query.get_or_404(id)
    return send_file(challenge.binary,
        mimetype      = 'application/octet-stream',
        download_name = challenge.name,
        as_attachment = True
    )


@blueprint.route('/challenges/<id>/edit', methods=['GET', 'POST'])
@require(admin=True)
def edit(id):
    challenge = Challenge.query.get_or_404(id)
    form = ChallengeForm(obj=challenge)
    if form.validate_on_submit():
        challenge.set_attributes(form)
        db.session.add(challenge)
        db.session.commit()

        flash('Challenge updated.')
        return redirect(url_for('challenges.index'))
    return render_template('challenges/edit.html', challenge=challenge, form=form)


@blueprint.route('/challenges/<id>', methods=['DELETE'])
@require(admin=True)
def delete(id):
    challenge = Challenge.filter_by(id=id).delete()
    flash('Challenge deleted.')
    return redirect(url_for('challenges.index'))

@blueprint.route('/challenges/<id>/submissions.json', methods=['GET'])
@require(user=True, running=True)
def submissions(id):
    subquery = db.session.query(
        db.func.max(Submission.id).label('submission_id'),
        Submission.user_id.label('user_id')
    ).select_from(
        Submission
    ).filter(
        Submission.challenge_id == id,
        Submission.owner_id     == current_user.get_owner_id()
    ).group_by(
        Submission.user_id
    ).subquery()

    query = db.session.query(
        Submission.id.label('id'),
        Account.name.label('author'),
        Submission.score.label('score')
    ).select_from(
        subquery
    ).join(
        Account, Account.id == subquery.c.user_id
    ).join(
        Submission, Submission.id == subquery.c.submission_id
    )

    result = [{'id': 0, 'author': 'Starter Code', 'score': 0}]
    for row in query.all():
        result.append({
            'id':     row.id,
            'author': row.author,
            'score':  row.score
        })

    return json.dumps(result)

@blueprint.route('/challenges/<cid>/submissions/<sid>.json', methods=['GET'])
@require(user=True, running=True)
def submission(cid, sid):
    if str(sid) == '0':
        challenge = Challenge.query.get_or_404(cid)
        return json.dumps({
            'id':     0,
            'source': readfile(challenge.decomp)
        })

    submission = Submission.query.filter_by(
        owner_id     = current_user.get_owner_id(),
        challenge_id = cid,
        id           = sid
    ).first_or_404()

    return json.dumps({
        'id':     sid,
        'source': submission.submission
    })

app/web/scores/routes.py
from flask import Blueprint, current_app, jsonify, render_template, request
import datetime

from ...lib.models  import Challenge
from ...lib.scoring import firsts, scores
from ...lib.timing  import now

blueprint = Blueprint('scores', __name__)


@blueprint.route('/scoreboard', methods=['GET'])
def html():
    endtime = current_app.config.get('END_TIME')
    if endtime and endtime <= now():
        official = (request.args.get('scores') == 'official')
        if not official: endtime = None
    else:
        official = None

    teams = scores(end=endtime)
    return render_template('scores/scoreboard.html', teams=teams, official=official)


@blueprint.route('/firstblood', methods=['GET'])
def firstblood():
    return render_template('scores/firstblood.html', submissions=firsts())


@blueprint.route('/scoreboard.json', methods=['GET'])
def json():
    endtime   = current_app.config.get('END_TIME')
    standings = []

    for team in scores(end=endtime):
        standings.append({
            'team':  team.name,
            'score': round(team.score, 2),
            'pos':   team.rank
        })

    return jsonify({'standings': standings})


@blueprint.route('/challenges/<id>/leaderboard', methods=['GET'])
def challenge(id):
    challenge = Challenge.query.get_or_404(id)
    endtime   = current_app.config.get('END_TIME')
    if endtime and endtime <= now():
        official = (request.args.get('scores') == 'official')
        if not official: endtime = None
    else:
        official = None

    teams = scores(end=endtime, challenge_id=id)
    return render_template('scores/challenge.html', teams=teams, official=official, challenge=challenge)

app/web/users/routes.py
import datetime

from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user

from ...lib.models  import db, Account, UserFollowup, UserInfo
from ...lib.require import require
from ...lib.scoring import user_solves
from ...lib.timing  import now

from .forms import NewUserForm, UserFollowupForm, UserInfoForm

blueprint = Blueprint('users', __name__)

@blueprint.route('/users', methods=['GET'])
def index():
    team  = db.aliased(Account)
    users = Account.query.filter_by(user=True)
    if not current_user.is_admin():
        users = users.filter_by(hidden=False, banned=False)
    users = users.join(Account.team.of_type(team), isouter=True).order_by(Account.name)
    return render_template('users/index.html', users=users.all())


@blueprint.route('/users/info', methods=['GET', 'POST'])
@require(user=True)
def info():
    if current_user.info_id is not None:
        flash('You already filled that out.')
        return redirect(url_for('challenges.index'))

    form = UserInfoForm()
    if form.validate_on_submit():
        current_user.info = UserInfo.from_form(form)
        db.session.add(current_user.info)
        db.session.add(current_user)
        db.session.commit()

        flash('Thank you for helping out!')
        return redirect(url_for('challenges.index'))

    return render_template('users/info.html', form=form)


# @blueprint.route('/users/followup', methods=['GET', 'POST'])
@require(user=True)
def followup():
    if current_user.followup_id is not None:
        flash('You already filled that out.')
        return redirect(url_for('challenges.index'))

    form = UserFollowupForm()
    if form.validate_on_submit():
        current_user.followup = UserFollowup.from_form(form)
        db.session.add(current_user.followup)
        db.session.add(current_user)
        db.session.commit()

        flash('Thanks for the feedback!')
        return redirect(url_for('challenges.index'))

    return render_template('users/followup.html', form=form)


@blueprint.route('/users/new', methods=['GET', 'POST'])
@require(user=False)
def new():
    form = NewUserForm()
    if form.validate_on_submit():
        user = Account.from_form(form, include=['password'], ignore=['disclaimer'])
        user.created_at = now()
        user.user = True
        if not Account.query.count():
            user.admin  = True
            user.hidden = True
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash('Welcome to the game!')
        # return redirect(url_for('challenges.index'))
        return redirect(url_for('users.info'))

    return render_template('users/new.html', form=form)


@blueprint.route('/users/<id>', methods=['GET'])
def show(id):
    user = Account.query.filter_by(id=id, user=True).first_or_404()
    return render_template('users/show.html', user=user, solves=user_solves(id))

app/templates/scores/challenge.html
{% extends "layout.html" %}

{% block style %}
table td:nth-child(3) {
  text-align: right;
}
{% endblock %}

{% block content %}
<h1>{{ challenge.name }}</h1>
<div class="subhead">
  <a href="{{ url_for('challenges.show', id=challenge.id) }}">play this challenge</a>
</div>

{% if official == True %}
<p class="subsubhead">These are the <strong>official</strong> scores as of
the end of the competition. If you're still playing, you can see your unofficial
scores <a href="{{ url_for('scores.challenge', id=challenge.id) }}">here</a>.</p>
{% elif official == False %}
<p class="subsubhead">These are <strong>unofficial</strong> scores, including
submissions from after the end of the competition.  You can find the official scores
<a href="{{ url_for('scores.challenge', id=challenge.id, scores='official') }}">here</a>.</p>
{% endif %}

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Player</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
{% for account in teams %}
    <tr>
      <td>{{ account.rank | ordinal }}</td>
      <td>
{% if account.is_user %}
        <img width="16px" src="/static/icons/user.svg" title="Solo Player" />
        <a href="{{ url_for('users.show', id=account.id) }}">{{ account.name }}</a>
{% else %}
        <img width="16px" src="/static/icons/team.svg" title="Team" />
        <a href="{{ url_for('teams.show', id=account.id) }}">{{ account.name }}</a>
{% endif %}
        <span class="id">#{{ account.id }}</span>
      </td>
      <td>{{ account.score | float(2) }}</td>
    </tr>
{% endfor %}
{% if not teams %}
    <tr class="placeholder">
      <td colspan="999">no submissions</td>
    </tr>
{% endif %}

  </tbody>
</table>
{% endblock %}

app/templates/scores/firstblood.html
{% extends "layout.html" %}

{% block style %}
table td:nth-child(3) {
  text-align: right;
}
{% endblock %}

{% block content %}
<h1>First Blood</h1>
<!-- <div class="subhead"></div> -->

<table>
  <thead>
    <tr>
      <th>Challenge</th>
      <th>Player</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
{% for submission in submissions %}
    <tr>
      <td>
        <a href="{{ url_for('challenges.show', id=submission.challenge.id) }}">{{ submission.challenge.name }}</a>
        <span class="id">#{{ submission.challenge.id }}</span>
      </td>
      <td>
{% if submission.owner.user %}
        <img width="16px" src="/static/icons/user.svg" title="Solo Player" />
        <a href="{{ url_for('users.show', id=submission.owner.id) }}">{{ submission.owner.name }}</a>
{% else %}
        <img width="16px" src="/static/icons/team.svg" title="Team" />
        <a href="{{ url_for('teams.show', id=submission.owner.id) }}">{{ submission.owner.name }}</a>
{% endif %}
        <span class="id">#{{ submission.owner.id }}</span>
      </td>
      <td>{{ submission.created_at | datetime }}</td>
    </tr>
{% endfor %}
{% if not submissions %}
    <tr class="placeholder">
      <td colspan="999">no perfect submissions</td>
    </tr>
{% endif %}

  </tbody>
</table>
{% endblock %}

app/templates/scores/scoreboard.html
{% extends "layout.html" %}

{% block style %}
table td:nth-child(3) {
  text-align: right;
}
{% endblock %}

{% block content %}
<h1>Scoreboard</h1>

{% if official == True %}
<p class="subsubhead">These are the <strong>official</strong> scores as of
the end of the competition. If you're still playing, you can see your unofficial
scores <a href="{{ url_for('scores.html') }}">here</a>.</p>
{% elif official == False %}
<p class="subsubhead">These are <strong>unofficial</strong> scores, including
submissions from after the end of the competition.  You can find the official scores
<a href="{{ url_for('scores.html', scores='official') }}">here</a>.</p>
{% endif %}

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Player</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
{% for account in teams %}
    <tr>
      <td>{{ account.rank | ordinal }}</td>
      <td>
{% if account.is_user %}
        <img width="16px" src="/static/icons/user.svg" title="Solo Player" />
        <a href="{{ url_for('users.show', id=account.id) }}">{{ account.name }}</a>
{% else %}
        <img width="16px" src="/static/icons/team.svg" title="Team" />
        <a href="{{ url_for('teams.show', id=account.id) }}">{{ account.name }}</a>
{% endif %}
        <span class="id">#{{ account.id }}</span>
      </td>
      <td>{{ account.score | float(2) }}</td>
    </tr>
{% endfor %}
{% if not teams %}
    <tr class="placeholder">
      <td colspan="999">no submissions</td>
    </tr>
{% endif %}

  </tbody>
</table>
{% endblock %}